# Generated by Django 4.1.7 on 2023-03-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, unique=True)),
                ('courses', models.ManyToManyField(to='college_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('GENDER', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=255)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('MAIL_ID', models.CharField(max_length=255)),
                ('ADDRESS', models.TextField(max_length=1000)),
                ('COURSE', models.CharField(default='B.Sc', max_length=255, null=True)),
                ('PURPOSE', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return')], max_length=255)),
                ('MATERIAL', models.CharField(max_length=255)),
                ('DEPARTMENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_app.department')),
            ],
        ),
    ]
